# https://prometheus.io/docs/prometheus/latest/configuration/configuration
# https://yunlzheng.gitbook.io/prometheus-book
#
global:
  scrape_interval: 15s     # Set scrape interval. Default 1m.
  scrape_timeout: 10s      # Set scrape request times out. Default 10s.
  evaluation_interval: 15s # Evaluate rules interval. Default 1m.
  external_labels:
    monitor: 'codelab'
  query_log_file: '/opt/prometheus/log/query.log'

rule_files:
  - '/opt/prometheus/conf/rules/cpu-node.rules.yml'
  #- "conf/*.rules"

scrape_configs:
  - job_name: 'prometheus'
    honor_labels: true
    honor_timestamps: true
    metrics_path: '/metrics'
    scheme: 'http'
    static_configs:
      - targets: ['192.168.5.220:9090']
        labels:
          group: 'standard'
          instance: 'default'

  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]
    dns_sd_configs:
      - names:
          - www.imssyang.com
        type: A
        port: 443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.5.220:9115
    static_configs:
      - targets:
        - http://www.imssyang.com
        - https://www.imssyang.com
        labels:
          group: 'system'
          instance: 'default'

  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.5.220:9100']
        labels:
          group: 'system'
          instance: 'default'

  - job_name: 'snmp_exporter'
    metrics_path: /snmp
    params:
      module: [if_mib]
    static_configs:
      - targets: ['192.168.5.220:9116']
        labels:
          group: 'system'
          instance: 'default'

  - job_name: 'statsd_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.5.220:9102']
        labels:
          group: 'system'
          instance: 'default'

  - job_name: 'python-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.5.220:8000']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['192.168.5.220:9093']

#remote_write:

#remote_read:

#storage:


